# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('p4-switch', ['p4simulator', 'csma', 'internet', 'applications', 'internet-apps'])
    obj.source = ['p4-switch.cc']

    obj = bld.create_ns3_program('ns3-demo', ['p4simulator', 'csma', 'internet', 'applications', 'internet-apps'])
    obj.source = ['ns3-demo.cc']