# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('p4-example', ['p4simulator', 'csma', 'internet', 'applications', 'internet-apps'])
    obj.source = ['p4-topo-test.cc']

    obj = bld.create_ns3_program('p4-echo-server', ['p4simulator', 'csma', 'internet', 'applications', 'internet-apps'])
    obj.source = ['p4-echo-server.cc']
